### ISSUE TITLE
Add access to /dev/video devices

### ISSUE THREAD

**Issue by albfan** [flathub/org.freedesktop.dabrain34.GstPipelineStudio#15]
It can be resolved with:

    flatpak --user override org.freedesktop.dabrain34.GstPipelineStudio --device=all

but can be annoying for many users expecting a node like v4l2src to just work

**Comment by dabrain34** [comment]
Thanks @albfan Can you create a PR for this change please ?

**Comment by albfan** [comment]
Sure!
